[package]
name = "cube"
version = "1.0.1"
edition = "2021"
description = "Rotates cubes lol"

[lib]
name = "libcube"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
